#!/bin/sh

tmp=/tmp/$(basename $0).$(date +%s).$$

sed -e '1s/awk/gawk/' validate-kv > $tmp-validate-kv.gawk
chmod +x $tmp-validate-kv.gawk

sed -e '1s/awk/nawk/' validate-kv > $tmp-validate-kv.nawk
chmod +x $tmp-validate-kv.nawk

# We can't use `mawk` because it cannot count multibyte characters correctly.
# sed -e '1s/awk/mawk/' validate-kv > $tmp-validate-kv.mawk
# chmod +x $tmp-validate-kv.mawk

cmds="./validate-kv $tmp-validate-kv.gawk $tmp-validate-kv.nawk"

for cmd in $cmds; do
  printf "###"
  printf "${cmd##*.}"
  echo "###"

  ls tests | while read dir; do
    dir=tests/$dir
    testname=$(basename $dir)
    printf "  Running test $testname ... "
    expected_exit_code=$(cat $dir/exit-code)
    $cmd $dir/rule $dir/data > $tmp-$testname-stdout
    if [ $? -ne $expected_exit_code ]; then echo "NG"; exit 1; fi
    diff -u $dir/stdout $tmp-$testname-stdout
    if [ $? -eq 0 ]; then echo "OK"; else echo "NG"; exit 1; fi
  done
done

rm -f $tmp-*
