#!/bin/sh

install_dir="/usr/local/bin"
project_root_dir="$(d=${0%/*}/; [ "_$d" = "_$0/" ] && d='./'; cd "$d"; pwd)"
cd "$project_root_dir/cmds"

cmds='
age/age
argon2/pw-needs-rehash
argon2/pwhash
argon2/pwverify
# assert-kv/assert-kv 
cookie2kv/cookie2kv
embed/embed
embed-f/embed-f
embed-kv/embed-kv
embed-l/embed-l
escape/escape
escape/unescape
escape-html/escape-html
form2kv/form2kv
md2html/md2html
merge-kv/merge-kv
readkv/readkv
self/self
sqlexec/sqlread
sqlexec/sqlwrite
urldecode/urldecode
urlencode/urlencode
unhide/unhide
validate-kv/validate-kv
'

for cmd in $cmds; do
  if [ -z "$cmd" ]; then continue; fi
  if [ "${cmd:0:1}" = '#' ]; then continue; fi

  echo "Installing $cmd"
  sudo rm -f "$install_dir/$cmd"
  sudo cp -f "$cmd" "$install_dir"
done


cd "$project_root_dir/shellshoccar_cmds"
cmds='
mkcookie
sessionf
'

for cmd in $cmds; do
  if [ -z "$cmd" ]; then continue; fi
  if [ "${cmd:0:1}" = '#' ]; then continue; fi

  echo "Installing $cmd"
  sudo rm -f "$install_dir/$cmd"
  sudo cp -f "$cmd" "$install_dir"
done
