#!/bin/sh

##########################################################################
# Prepare Test
thisd=$(dirname $(readlink -f $0))
cd $thisd
tmp=/tmp/$(basename $0).$(date +%s).$$
cmd="./bin/escape-html"

./build

ls tests |
while read c; do
  printf "%-25s" $c

  in=tests/$c/in
  out=tests/$c/out

  $cmd < $in > $tmp-actual
  diff -u $out $tmp-actual
  if [ $? -ne 0 ]; then echo "... NG"; exit 1; fi
  echo "... OK"
done
