#!/usr/bin/env python
#coding: utf-8

import os
import sys
import sqlite3

_usage = "sqlread <sql-file> <parameter-file>"
_version = "Sat Nov 30 16:32:58 JST 2024 fujis"
_docs = "https://github.com/ppdx999/cmdset"


def read_file(file):
    if file == '-':
        file = "/dev/fd/0"
    with open(file) as f:
        return f.read()


def kv2dict(kv):
    rdict = {}
    for line in kv.split('\n'):
        if not line:
            continue
        k, v = line.split(' ', 1)
        rdict[k.strip()] = v.strip()
    return rdict


def take(array, i, default=None):
    return array[i] if len(array) > i else default


def escape_chars(s):
    s = s.replace('\n', '\\n')
    s = s.replace('\t', '\\t')
    s = s.replace('\r', '\\r')
    s = s.replace('_', '\\_')
    s = s.replace(' ', '_')
    return s


if __name__ == '__main__':
    a1 = take(sys.argv, 1, '-')
    a2 = take(sys.argv, 2, None)
    if a1 in ['-h', '--help', '-v', '--version']:
        print("sqlread - print sql query result", file=sys.stderr)
        print("", file=sys.stderr)
        print("Usage: %s" % _usage, file=sys.stderr)
        print("Version: %s" % _version, file=sys.stderr)
        print("Docs: %s" % _docs, file=sys.stderr)
        sys.exit(1)

    sql = read_file(a1)
    params = kv2dict(read_file(a2)) if a2 else None

    database_url = os.environ.get('DATABASE_URL')
    if not database_url:
        print("Error: DATABASE_URL is not set", file=sys.stderr)
        sys.exit(1)

    engine = database_url.split(':')[0]
    if engine == 'sqlite3':
        conn = sqlite3.connect(database_url.split(':///')[1])
        cursor = conn.cursor()
        if params:
            cursor.execute(sql, params)
        else:
            cursor.execute(sql)

        for row in cursor.fetchall():
            for i, col in enumerate(row):
                if i > 0:
                    print(" ", end="")
                print(escape_chars(str(col)), end="")
            print("")

        cursor.close()
        conn.close()
    else:
        msg = "Error: unsupported database engine %s" % engine
        print(msg, file=sys.stderr)
        sys.exit(1)
