#!/usr/bin/env python
#coding: utf-8

import sys
from argon2 import PasswordHasher

_usage = "pw-needs-rehash <hashed_password>"
_version = "Sat Nov 30 16:32:58 JST 2024 fujis"
_homepage = "https://github.com/ppdx999/cmdset"

if __name__ == '__main__':
    if sys.argv[1] in ['-h', '--help', '-v', '--version']:
        print("pw-needs-rehash - verify password", file=sys.stderr)
        print("", file=sys.stderr)
        print("Usage: %s" % _usage, file=sys.stderr)
        print("Version: %s" % _version, file=sys.stderr)
        print("Homepage: %s" % _homepage, file=sys.stderr)
        sys.exit(1)

    if len(sys.argv) != 2:
        print("Usage: %s" % _usage, file=sys.stderr)
        sys.exit(1)

    exit(
        int(
            not PasswordHasher().check_needs_rehash(
                sys.argv[1]
            )
        )
    )
