#!/usr/bin/env python
#coding: utf-8

import sys
from functools import reduce
from argon2 import PasswordHasher

_usage = "pwhash <file>"
_version = "Sat Nov 30 16:32:58 JST 2024 fujis"
_homepage = "https://github.com/ppdx999/cmdset"


def usage():
    print("Usage: %s" % _usage, file=sys.stderr)
    print("Version: %s" % _version, file=sys.stderr)
    print("Homepage: %s" % _homepage, file=sys.stderr)


def readline(f):
    if f == '-':
        f = "/dev/fd/0"
    with open(f, 'r') as f:
        return f.readline().strip()


def take(array, i, default=None):
    return array[i] if len(array) > i else default


def pipe(x, *fs):
    return reduce(lambda x, f: f(x), fs, x)


if __name__ == '__main__':
    a1 = take(sys.argv, 1, '-')
    if a1 in ['-h', '--help', '-v', '--version']:
        usage()
        sys.exit(1)

    pipe(
        a1,
        readline,
        PasswordHasher().hash,
        print
    )
