#!/usr/bin/env python
#coding: utf-8

import sys
from argon2 import PasswordHasher

_usage = "pwverify <hashed_password> <raw_password>"
_version = "Sat Nov 30 16:32:58 JST 2024 fujis"
_homepage = "https://github.com/ppdx999/cmdset"

if __name__ == '__main__':
    if sys.argv[1] in ['-h', '--help', '-v', '--version']:
        print("pwverify - verify password", file=sys.stderr)
        print("", file=sys.stderr)
        print("Usage: %s" % _usage, file=sys.stderr)
        print("Version: %s" % _version, file=sys.stderr)
        print("Homepage: %s" % _homepage, file=sys.stderr)
        sys.exit(1)

    if len(sys.argv) != 3:
        print("Usage: %s" % _usage, file=sys.stderr)
        sys.exit(1)

    try:
        PasswordHasher().verify(sys.argv[1], sys.argv[2])
    except Exception:
        sys.exit(1)

    sys.exit(0)
