#!/usr/bin/env -S awk -f ${_} --

######################################################################
# Init
BEGIN {
  # Remove the script path
  delete ARGV[1]
  # Parse Options
  if ( ARGV[2] == "-h" || ARGV[2] == "--help"    ||
       ARGV[2] == "-v" || ARGV[2] == "--version" ||
       ARGC == 1       \
  ){
    print "embed-f - embed data into a template file using a keyword" > "/dev/stderr"
    print ""                                                          > "/dev/stderr"
    print "Usage: embed-f <keyword> <template-file> <data-file>"      > "/dev/stderr"
    print "Version: Sat Nov 30 16:32:58 JST 2024 fujis"               > "/dev/stderr"
    print "Homepage: https://github.com/ppdx999/cmdset"               > "/dev/stderr"
    exit 1
  }
  keyword = ARGV[2] ; delete ARGV[2]
  datafile = ARGV[4]; delete ARGV[4]
}

######################################################################
# Main Routine
{
  if (index($0, keyword)) {
    system("cat " datafile)
  } else {
    print
  }
}
