#!/bin/sh

##########################################################################
# Prepare Test
thisd=$(dirname $(readlink -f $0))
cd $thisd
tmp=/tmp/$(basename $0).$(date +%s).$$
cmd="./bin/embed-f"

./build

ls tests |
while read c; do
  printf "%-25s" $c

  keyword=tests/$c/keyword
  data=tests/$c/data
  template=tests/$c/template
  expect=tests/$c/expect

  $cmd $(cat $keyword) $data $template > $tmp-actual
  diff -u $expect $tmp-actual
  if [ $? -ne 0 ]; then echo "... NG"; exit 1; fi
  echo "... OK"
done

rm -f $tmp-*
