#!/bin/sh

##########################################################################
# Prepare Test
thisd=$(dirname $(readlink -f $0))
cd $thisd
tmp=/tmp/$(basename $0).$(date +%s).$$
cmd="./render"

ls tests |
while read c; do
  printf "%-25s" $c

  template=tests/$c/template
  data=tests/$c/data
  expected=tests/$c/expected

  kv2json $data | $cmd - $template > $tmp-actual
  diff -u $expected $tmp-actual
  if [ $? -ne 0 ]; then echo "... NG"; exit 1; fi
  echo "... OK"
done
