#!/usr/bin/env -S awk -f ${_} --

######################################################################
# Init
function printerr(msg) {
    print msg > "/dev/stderr"
}

BEGIN {
  # Remove the script path
  delete ARGV[1]
  # Parse Options
  if ( \
    ARGV[i] == "-h"        ||
    ARGV[i] == "--help"    ||
    ARGV[i] == "-v"        ||
    ARGV[i] == "--version" ||
    ARGC == 1              \
  ){
    printerr("embed - embed data into a template file using a keyword")
    printerr("")
    printerr("Usage: embed <keyword> <template-file> <data-file>")
    exit 1
  }
  keyword = ARGV[2] ; delete ARGV[2]
  datafile = ARGV[4]; delete ARGV[4]
}

######################################################################
# Main Routine
{
  if (index($0, keyword)) {
    system("cat " datafile)
  } else {
    print
  }
}
