#!/bin/sh

##########################################################################
# Prepare Test
tmp=/tmp/$(basename $0).$(date +%s).$$

sed -e '1s/awk/gawk/' urldecode > $tmp-urldecode.gawk
chmod +x $tmp-urldecode.gawk

sed -e '1s/awk/nawk/' urldecode > $tmp-urldecode.nawk
chmod +x $tmp-urldecode.nawk

sed -e '1s/awk/mawk/' urldecode > $tmp-urldecode.mawk
chmod +x $tmp-urldecode.mawk

cmds="./urldecode $tmp-urldecode.gawk $tmp-urldecode.nawk $tmp-urldecode.mawk"

run_test() {
  if [ "$(echo "$2" | $1)" != "$3" ]; then
    echo "Failed" $2 $3
    echo "$2" | $1
    exit 1
  fi
}

##########################################################################
# Test Main Routine
for cmd in $cmds; do

printf "%12s: " ${cmd##*.}

run_test $cmd "hello%2C+world" "hello, world"
run_test $cmd 'newline
secondline' 'newline
secondline'
run_test $cmd 'username%3Dguest%26password%3Dguest' 'username=guest&password=guest'
run_test $cmd "%E3%81%82" "あ"
run_test $cmd "%E3%81%93%E3%82%93%E3%81%AB%E3%81%A1%E3%81%AF%E3%80%81%E4%B8%96%E7%95%8C" "こんにちは、世界"

echo "OK"

done

##########################################################################
# Clean up and Exit
rm -f $tmp-*
exit 0
